title: I Doubt It - A Game Analysis
description: LAMAS Project 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

url: "https://shaniyahali.github.io"
baseurl: "/LAMAS"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
